/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Organizes the CMS library. It does not change the immutable R2 object key.
   */
  assetGroup: 'website' | 'project' | 'identity' | 'editorial' | 'archive';
  /**
   * Optional cross-reference for project-library images; images may be reused.
   */
  relatedProjects?: (number | Project)[] | null;
  /**
   * A concise description for screen readers and image fallbacks.
   */
  alt: string;
  caption?: string | null;
  /**
   * Photographer, studio, or rights attribution when needed.
   */
  credit?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Generated from the title; edit it only when the public URL must differ.
   */
  slug: string;
  /**
   * Classifies the project presentation for future template variations.
   */
  layout: 'editorial' | 'gallery' | 'technical';
  /**
   * For example: Completed, In development, or Competition.
   */
  status: string;
  location: string;
  year: number;
  /**
   * For example: Architecture / Interiors / Landscape.
   */
  scope: string;
  /**
   * The shared project summary. It appears in Our Work and at the beginning of the project page.
   */
  description: string;
  /**
   * Used as the large Our Work image and the project-page cover.
   */
  coverImage: number | Media;
  /**
   * The second image shown beside this project in the Our Work archive.
   */
  archiveDetailImage: number | Media;
  /**
   * Optional. The primary image is reused when this is empty.
   */
  closingImage?: (number | null) | Media;
  /**
   * Optional longer copy shown after the shared description on the project page only.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Add and reorder the project-page narrative, images, and galleries.
   */
  sections?: (ProjectHeroBlock | TextImageBlock | ImageGalleryBlock)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectHeroBlock".
 */
export interface ProjectHeroBlock {
  eyebrow?: string | null;
  heading: string;
  summary?: string | null;
  image?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'projectHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextImageBlock".
 */
export interface TextImageBlock {
  heading?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (number | null) | Media;
  imagePosition?: ('right' | 'left') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textImage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGalleryBlock".
 */
export interface ImageGalleryBlock {
  heading?: string | null;
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageGallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  assetGroup?: T;
  relatedProjects?: T;
  alt?: T;
  caption?: T;
  credit?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?: T;
  status?: T;
  location?: T;
  year?: T;
  scope?: T;
  description?: T;
  coverImage?: T;
  archiveDetailImage?: T;
  closingImage?: T;
  intro?: T;
  sections?:
    | T
    | {
        projectHero?: T | ProjectHeroBlockSelect<T>;
        textImage?: T | TextImageBlockSelect<T>;
        imageGallery?: T | ImageGalleryBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectHeroBlock_select".
 */
export interface ProjectHeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  summary?: T;
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextImageBlock_select".
 */
export interface TextImageBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  image?: T;
  imagePosition?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGalleryBlock_select".
 */
export interface ImageGalleryBlockSelect<T extends boolean = true> {
  heading?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    eyebrow?: string | null;
    title: string;
    summary?: string | null;
    image: number | Media;
  };
  /**
   * Controls the image and statement directly below the homepage hero. This image is independent from the hero and project images.
   */
  position: {
    /**
     * Portrait-oriented or crop-safe architectural imagery works best here.
     */
    image: number | Media;
    /**
     * Use line breaks to control the three-line editorial heading.
     */
    heading: string;
    descriptionPrimary: string;
    descriptionSecondary: string;
  };
  /**
   * Controls every line of copy and both portraits in the homepage People section. The two-person layout remains fixed.
   */
  people: {
    sectionLabel: string;
    sectionSummary: string;
    heading: string;
    description: string;
    /**
     * Appears as the lower portrait on the left at desktop widths.
     */
    personOne: {
      /**
       * Use a portrait-oriented or crop-safe image.
       */
      image: number | Media;
      name: string;
      role: string;
      description: string;
    };
    /**
     * Appears as the upper portrait on the right at desktop widths.
     */
    personTwo: {
      /**
       * Use a portrait-oriented or crop-safe image.
       */
      image: number | Media;
      name: string;
      role: string;
      description: string;
    };
  };
  /**
   * Controls the full-width image and two text values immediately below the People section. The reveal animation and layout remain fixed.
   */
  closing: {
    /**
     * Landscape or crop-safe architectural imagery works best here.
     */
    image: number | Media;
    /**
     * Use a line break to control the two-line heading.
     */
    heading: string;
    label: string;
  };
  /**
   * The star project shown directly after the hero.
   */
  featuredProject?: (number | null) | Project;
  /**
   * Choose and drag projects into the exact order they should appear on the homepage.
   */
  projectOrder?: (number | Project)[] | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        summary?: T;
        image?: T;
      };
  position?:
    | T
    | {
        image?: T;
        heading?: T;
        descriptionPrimary?: T;
        descriptionSecondary?: T;
      };
  people?:
    | T
    | {
        sectionLabel?: T;
        sectionSummary?: T;
        heading?: T;
        description?: T;
        personOne?:
          | T
          | {
              image?: T;
              name?: T;
              role?: T;
              description?: T;
            };
        personTwo?:
          | T
          | {
              image?: T;
              name?: T;
              role?: T;
              description?: T;
            };
      };
  closing?:
    | T
    | {
        image?: T;
        heading?: T;
        label?: T;
      };
  featuredProject?: T;
  projectOrder?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}